// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects_PhongChongMaTuy.Models;

public partial class CampaignParticipant
{
    public int Id { get; set; }

    public int? CampaignId { get; set; }

    public int? UserId { get; set; }

    public string Feedback { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Campaign Campaign { get; set; }

    public virtual User User { get; set; }
}