// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects_PhongChongMaTuy.Models;

public partial class Campaign
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Organizer { get; set; }

    public virtual ICollection<CampaignParticipant> CampaignParticipants { get; set; } = new List<CampaignParticipant>();
}