// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects_PhongChongMaTuy.Models;

public partial class ConsultantSlot
{
    public int Id { get; set; }

    public int? ConsultantId { get; set; }

    public DateOnly? WorkingDate { get; set; }

    public int? SlotId { get; set; }

    public bool? IsBooked { get; set; }

    public virtual User Consultant { get; set; }

    public virtual Slot Slot { get; set; }
}