// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects_PhongChongMaTuy.Models;

public partial class ConsultantInfo
{
    public int UserId { get; set; }

    public string AvatarUrl { get; set; }

    public int? ExperienceYears { get; set; }

    public string Degree { get; set; }

    public string Certificate { get; set; }

    public string Languages { get; set; }

    public decimal? PricePerSession { get; set; }

    public string WorkingDays { get; set; }

    public TimeOnly? WorkingStart { get; set; }

    public TimeOnly? WorkingEnd { get; set; }

    public string Specialties { get; set; }

    public string Methods { get; set; }

    public decimal? Rating { get; set; }

    public int? ReviewCount { get; set; }

    public virtual User User { get; set; }
}