// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects_PhongChongMaTuy.Models;

public partial class Lesson
{
    public int Id { get; set; }

    public int? CourseId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public int? OrderNo { get; set; }

    public virtual Course Course { get; set; }
}